---
language: python
python: "2.7"
node_js:
  - "7"

sudo: required
dist: xenial

before_install:
  # Update APT caches.
  - sudo apt-get update
  -  sudo apt-get purge postgr*
  -  sudo apt-get purge virtualbox*
  -  sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
  -  sudo apt-get -y install build-essential
  -  sudo apt-get -y --force-yes install linux-headers-`uname -r`
  # Install Ansible.
  - pip install ansible
  - ansible --version
  # Install VirtualBox.
  - wget http://download.virtualbox.org/virtualbox/5.1.14/virtualbox-5.1_5.1.14-112924~Ubuntu~xenial_amd64.deb
  - sudo apt-get install libqt5x11extras5 -y
  - sudo dpkg -i virtualbox-5.1_5.1.14-112924~Ubuntu~xenial_amd64.deb
  # Install Vagrant.
  - wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
  - sudo dpkg -i vagrant_1.9.1_x86_64.deb
  - vagrant -v
  # Install vagrant plugins.
  - vagrant plugin install vagrant-hostsupdater
  - vagrant plugin install vagrant-auto_network

install:
  - echo "Package installation will be here..."
before_script:
  - echo "Directory preparation will be here..."

script:
